// Trading glossary content. Plain-English, education-only — not advice.
export type GlossaryCategory =
  | "Market Structure"
  | "Order Flow"
  | "Technical Analysis"
  | "Risk Management"
  | "Futures-Specific"
  | "Psychology";

export type Term = {
  term: string;
  category: GlossaryCategory;
  definition: string;
  why: string;
  example: string;
};

export const GLOSSARY_CATEGORIES: GlossaryCategory[] = [
  "Market Structure", "Order Flow", "Technical Analysis",
  "Risk Management", "Futures-Specific", "Psychology",
];

export const GLOSSARY: Term[] = [
  // ---- Market Structure ----
  { term: "Swing High / Swing Low", category: "Market Structure",
    definition: "A local peak (high) or trough (low) confirmed by lower/higher bars on both sides.",
    why: "Swings define trend direction and where stops cluster; breaking them signals structure change.",
    example: "Price makes 18,050, pulls back, then can't exceed it — 18,050 is a swing high." },
  { term: "Break of Structure (BOS)", category: "Market Structure",
    definition: "Price closing beyond a confirmed prior swing in the trend direction.",
    why: "Signals continuation — the path of least resistance is still that way.",
    example: "In an uptrend, price closes above the last swing high → bullish BOS." },
  { term: "Change of Character (CHoCH)", category: "Market Structure",
    definition: "The first break against the prevailing trend's structure.",
    why: "An early warning that a trend may be ending or reversing.",
    example: "After higher-highs, price breaks the last higher-low → potential top." },
  { term: "Higher High / Higher Low", category: "Market Structure",
    definition: "Successive swings each above the prior — the signature of an uptrend (inverse for downtrend).",
    why: "It's the simplest objective definition of 'trend'.",
    example: "HH 18,050 → HL 17,990 → HH 18,120 = healthy uptrend." },
  { term: "Range / Consolidation", category: "Market Structure",
    definition: "Price oscillating between a horizontal support and resistance with no net progress.",
    why: "Breakout strategies fail here; mean-reversion works. Knowing you're in a range is half the battle.",
    example: "Price bounces between 17,900 and 18,000 for two hours." },
  { term: "Prior-Day High / Low (PDH/PDL)", category: "Market Structure",
    definition: "The highest and lowest prints of the previous session.",
    why: "The most-watched reference levels — breaks and rejections there are meaningful.",
    example: "Price reclaims yesterday's high and holds it on a retest." },

  // ---- Order Flow ----
  { term: "Liquidity", category: "Order Flow",
    definition: "Resting orders (stops and limits) clustered at obvious levels.",
    why: "Markets gravitate toward liquidity; big players need it to fill size.",
    example: "Stops just above an obvious high are a liquidity pool." },
  { term: "Liquidity Sweep / Stop Hunt", category: "Order Flow",
    definition: "A poke beyond an obvious high/low that triggers stops, then reverses.",
    why: "Traps breakout traders and fills large orders; a sweep-and-reclaim is a reversal tell.",
    example: "Price spikes 3 ticks over the high, then closes back below it." },
  { term: "Fair Value Gap (FVG)", category: "Order Flow",
    definition: "A 3-candle imbalance where price moved so fast it left an untraded gap.",
    why: "Often partially 'filled' later, offering a defined retest entry.",
    example: "Candle 1 high < candle 3 low leaves a gap price revisits." },
  { term: "Order Block (OB)", category: "Order Flow",
    definition: "The last opposing candle before an impulsive move — a zone of prior aggression.",
    why: "Resting orders may sit there, so price often reacts on a return.",
    example: "Last down candle before a sharp rally; price dips back to it and bounces." },
  { term: "Absorption", category: "Order Flow",
    definition: "Large passive orders soaking up aggressive market orders without price moving much.",
    why: "Signals a strong hand defending a level; a breakout attempt that stalls may reverse.",
    example: "Heavy selling hits a level but price barely drops — buyers are absorbing." },
  { term: "VWAP (Volume-Weighted Average Price)", category: "Order Flow",
    definition: "The average price weighted by volume, reset each session.",
    why: "An institutional fair-value benchmark; price tends to revert to it in ranges.",
    example: "Price stretched 1.5 ATR above VWAP often snaps back toward it." },

  // ---- Technical Analysis ----
  { term: "ATR (Average True Range)", category: "Technical Analysis",
    definition: "The average size of a bar's range over N periods — a volatility measure.",
    why: "Size positions and set stops in ATR units, not fixed points, so risk scales with conditions.",
    example: "ATR(14) = 20 pts → a 1.5×ATR stop is 30 pts." },
  { term: "ADX / DI", category: "Technical Analysis",
    definition: "ADX measures trend strength; +DI/−DI show direction.",
    why: "A filter for which strategy is even allowed: trend systems want high ADX, ranges want low.",
    example: "ADX > 25 with +DI over −DI = a real uptrend." },
  { term: "EMA (Exponential Moving Average)", category: "Technical Analysis",
    definition: "A moving average weighting recent prices more heavily.",
    why: "Defines trend and a dynamic pullback zone; the 20/50 are common.",
    example: "Price pulls back to a rising 20-EMA and resumes up." },
  { term: "RSI", category: "Technical Analysis",
    definition: "A 0–100 momentum oscillator; >70 'overbought', <30 'oversold'.",
    why: "Useful for mean-reversion timing in ranges; misleading in strong trends.",
    example: "RSI < 30 while price is stretched below VWAP in a range = fade candidate." },
  { term: "Opening Range (ORB)", category: "Technical Analysis",
    definition: "The high/low of the first N minutes after the cash open.",
    why: "Defines the day's initial balance; breaks of it can start the trend day.",
    example: "Break above the 15-min opening-range high on expansion." },
  { term: "OTE (Optimal Trade Entry)", category: "Technical Analysis",
    definition: "The 0.618–0.786 retracement zone of an impulse leg.",
    why: "A confluence area where pullback entries offer better R:R — a zone people watch, not physics.",
    example: "Price retraces 70% of a leg into the OTE and resumes." },

  // ---- Risk Management ----
  { term: "R-multiple (R)", category: "Risk Management",
    definition: "Profit/loss measured in units of the amount risked on the trade.",
    why: "Normalizes results across trade sizes — the only honest way to compare trades.",
    example: "Risk $100, make $200 → +2R; lose the planned risk → −1R." },
  { term: "Expectancy", category: "Risk Management",
    definition: "Average R per trade = (win% × avgWinR) − (loss% × avgLossR).",
    why: "Positive expectancy is the goal; a high win rate with negative expectancy still bleeds.",
    example: "60% wins at +1R, 40% losses at −2R → expectancy −0.2R (a loser)." },
  { term: "Profit Factor", category: "Risk Management",
    definition: "Gross profit ÷ gross loss.",
    why: "Above 1.0 is profitable; it captures payoff asymmetry win rate hides.",
    example: "$3,000 profit / $2,000 loss = 1.5 profit factor." },
  { term: "Max Drawdown", category: "Risk Management",
    definition: "The largest peak-to-trough decline of the equity curve.",
    why: "It's what actually blows accounts; a strategy is only as good as its worst stretch.",
    example: "Equity peaks at +8R then falls to +2R → 6R drawdown." },
  { term: "Position Sizing (1% rule)", category: "Risk Management",
    definition: "Risking a fixed small fraction of equity (e.g. 1%) per trade.",
    why: "Caps the damage of any single loss and any losing streak.",
    example: "$50k × 1% = $500 risk; with a 25-pt stop on MNQ ($2/pt) → 10 contracts." },
  { term: "Reward:Risk (R:R)", category: "Risk Management",
    definition: "Distance to target ÷ distance to stop.",
    why: "Higher R:R lets you be right less often and still profit.",
    example: "60-pt target, 30-pt stop = 2:1 — break-even at a 33% win rate." },

  // ---- Futures-Specific ----
  { term: "Tick & Point Value", category: "Futures-Specific",
    definition: "A tick is the minimum price increment; point value is the $ per 1.0 move per contract.",
    why: "Determines exactly what each trade is worth — core to sizing and P&L.",
    example: "MNQ: 0.25 tick, $2/point ($0.50/tick). MGC: 0.10 tick, $10/point." },
  { term: "Micro vs E-mini", category: "Futures-Specific",
    definition: "Micros (MNQ, MGC) are 1/10th the size of the E-mini (NQ, GC).",
    why: "Micros let you learn and size precisely with far less capital at risk.",
    example: "MNQ is 1/10 of NQ — ideal for practice-sized risk." },
  { term: "Initial / Maintenance Margin", category: "Futures-Specific",
    definition: "Cash required to open (initial) and hold (maintenance) a futures position.",
    why: "Leverage cuts both ways; margin defines how much exposure your account allows.",
    example: "A micro may need a few hundred dollars of margin per contract." },
  { term: "Contract Roll / Expiry", category: "Futures-Specific",
    definition: "Futures expire; traders 'roll' to the next contract month.",
    why: "Around roll, volume and reference levels shift between contracts.",
    example: "Front-month NQ rolls quarterly (Mar/Jun/Sep/Dec)." },
  { term: "RTH vs ETH", category: "Futures-Specific",
    definition: "Regular Trading Hours (cash session) vs Extended/overnight Hours.",
    why: "Liquidity, volatility and reliable levels differ; many setups assume RTH.",
    example: "The 09:30 ET cash open often sets the day's tone." },
  { term: "Killzone", category: "Futures-Specific",
    definition: "Higher-activity windows after the open (~09:30–11:00 ET) and afternoon (~14:00–15:30).",
    why: "A timing filter — setups in the killzone tend to have more follow-through.",
    example: "An ORB break inside the morning killzone." },

  // ---- Psychology ----
  { term: "FOMO (Fear of Missing Out)", category: "Psychology",
    definition: "Chasing a move you missed, entering late without a plan.",
    why: "Late, planless entries have poor R:R and are a top account-killer.",
    example: "Price runs 2R without you; you market-buy the top and get stopped." },
  { term: "Revenge Trading", category: "Psychology",
    definition: "Immediately re-entering to 'win back' a loss.",
    why: "Emotion replaces process; sizing and selection degrade fast.",
    example: "After a −1R, you double size on a marginal setup to get it back." },
  { term: "Tilt", category: "Psychology",
    definition: "An emotional state (anger/frustration) that wrecks decision-making.",
    why: "On tilt you ignore your plan; the fix is to stop, not to trade more.",
    example: "Two quick losses and you start clicking randomly — that's tilt." },
  { term: "Overtrading", category: "Psychology",
    definition: "Taking too many trades, often low-quality, out of boredom or to 'do something'.",
    why: "Costs and marginal setups erode any edge; fewer, better trades win.",
    example: "15 trades in a quiet, rangebound morning." },
  { term: "Loss Aversion", category: "Psychology",
    definition: "Feeling losses ~2× as strongly as equivalent gains.",
    why: "Drives moving stops and cutting winners early — the exact wrong reactions.",
    example: "You widen your stop 'just this once' to avoid being wrong." },
  { term: "Discipline / Process", category: "Psychology",
    definition: "Following a written plan regardless of the last outcome.",
    why: "Edge only shows up over many trades; process is the controllable variable.",
    example: "You skip a tempting trade because it fails one of your rules." },
];
